// TỆP SINH TỰ ĐỘNG — ĐỪNG SỬA TAY.
// Nguồn: SSI iBoard (https://iboard-query.ssi.com.vn/stock/exchange/hose), lọc stockType='s'
// Sinh lại: node scripts/harvest-hose-symbols.mjs
// Vì sao là file tĩnh chứ không gọi mạng: xem đầu scripts/harvest-hose-symbols.mjs
//
// Chỉ có sàn HOSE. Giá thị trường lấy từ Yahoo, mà Yahoo chỉ phục vụ HOSE qua hậu tố
// '.VN' — liệt kê mã HNX/UPCOM ở đây sẽ gợi ý những mã mà app không lấy được giá, tức là
// mời người dùng vào một chỗ chỉ để nhận thông báo "chưa có giá".
export const HOSE_SYMBOLS: readonly (readonly [symbol: string, name: string])[] = [
  ['AAA', 'Công ty Cổ phần Nhựa An Phát Xanh'],
  ['AAM', 'Công ty Cổ phần Thủy sản Mekong'],
  ['AAN', 'Công ty Cổ phần Lương thực A An'],
  ['AAT', 'Công ty Cổ phần Tập đoàn Tiên Sơn Thanh Hóa'],
  ['ABR', 'Công ty Cổ phần Đầu tư Nhãn hiệu Việt'],
  ['ABS', 'Công ty Cổ phần Dịch vụ Nông nghiệp Bình Thuận'],
  ['ABT', 'Công ty Cổ phần Xuất nhập khẩu Thủy sản Bến Tre'],
  ['ACB', 'Ngân hàng Thương mại Cổ phần Á Châu'],
  ['ACC', 'Công ty Cổ phần Đầu tư và Xây dựng Bình Dương ACC'],
  ['ACG', 'Công ty Cổ phần Gỗ An Cường'],
  ['ACL', 'Công ty Cổ phần Xuất Nhập Khẩu Thủy sản Cửu Long An Giang'],
  ['ADG', 'Công ty Cổ phần Clever Group'],
  ['ADP', 'Công ty Cổ phần Sơn Á Đông'],
  ['ADS', 'Công ty Cổ phần Damsan'],
  ['AFX', 'CTCP Xuất nhập khẩu Nông sản Thực phẩm An Giang'],
  ['AGG', 'Công ty Cổ phần Đầu tư và Phát triển Bất động sản An Gia'],
  ['AGR', 'Công ty Cổ phần Chứng khoán Agribank'],
  ['ANT', 'Công ty cổ phần Rau quả thực phẩm An Giang'],
  ['ANV', 'Công ty Cổ phần Nam Việt'],
  ['APG', 'Công ty Cổ phần Chứng khoán APG'],
  ['APH', 'Công ty Cổ phần Tập đoàn An Phát Holdings'],
  ['ASG', 'Công ty Cổ phần Tập đoàn ASG'],
  ['ASM', 'Công ty Cổ phần Tập đoàn Sao Mai'],
  ['ASP', 'Công ty Cổ phần Tập đoàn Dầu khí An Pha'],
  ['AST', 'Công ty Cổ phần Dịch vụ Hàng không Taseco'],
  ['BAF', 'Công ty Cổ phần Nông nghiệp BAF Việt Nam'],
  ['BCE', 'Công ty Cổ phần Xây dựng và Giao thông Bình Dương'],
  ['BCM', 'Tập đoàn Đầu tư và Phát triển Công nghiệp Becamex - CTCP'],
  ['BFC', 'Công ty Cổ phần Phân bón Bình Điền'],
  ['BHN', 'Tổng Công ty Cổ phần Bia – Rượu – Nước giải khát Hà Nội'],
  ['BIC', 'Tổng Công ty Bảo hiểm Ngân hàng Đầu tư và Phát triển Việt Nam'],
  ['BID', 'Ngân hàng Thương mại Cổ phần Đầu tư và Phát triển Việt Nam'],
  ['BKG', 'Công ty Cổ phần Đầu tư BKG Việt Nam'],
  ['BMC', 'Công ty Cổ phần Khoáng sản Bình Định'],
  ['BMI', 'Tổng Công ty Cổ phần Bảo Minh'],
  ['BMP', 'Công ty Cổ phần Nhựa Bình Minh'],
  ['BRC', 'Công ty Cổ phần Cao su Bến Thành'],
  ['BSI', 'Công ty Cổ phần Chứng khoán BIDV'],
  ['BSR', 'CÔNG TY CỔ PHẦN – TỔNG CÔNG TY LỌC HÓA DẦU VIỆT NAM'],
  ['BTP', 'Công ty Cổ phần Nhiệt điện Bà Rịa'],
  ['BTT', 'Công ty Cổ phần Thương mại – Dịch vụ Bến Thành'],
  ['BVB', 'Ngân hàng Thương mại Cổ phần Bản Việt'],
  ['BVH', 'Tập đoàn Bảo Việt'],
  ['BWE', 'Công ty Cổ phần - Tổng Công ty Nước – Môi trường Bình Dương'],
  ['C32', 'CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ XÂY DỰNG 3-2'],
  ['C47', 'Công ty Cổ phần Xây dựng 47'],
  ['CCC', 'Công ty Cổ phần Xây dựng CDC'],
  ['CCI', 'Công ty Cổ phần Đầu tư Phát triển Công nghiệp Thương mại Củ Chi'],
  ['CCL', 'Công ty Cổ phần Đầu tư và Phát triển Đô thị Dầu khí Cửu Long'],
  ['CDC', 'Công ty Cổ phần Chương Dương'],
  ['CHP', 'Công ty Cổ phần Thủy điện Miền Trung'],
  ['CIG', 'Công ty Cổ phần COMA18'],
  ['CII', 'Công ty Cổ phần Đầu tư Hạ tầng Kỹ thuật TP.HCM'],
  ['CKG', 'Công ty Cổ phần Tập đoàn CIC'],
  ['CLC', 'Công ty Cổ phần Cát Lợi'],
  ['CLL', 'Công ty Cổ phần Cảng Cát Lái'],
  ['CLW', 'Công ty Cổ phần Cấp nước Chợ Lớn'],
  ['CMG', 'Công ty Cổ phần Tập đoàn Công nghệ CMC'],
  ['CMV', 'Công ty Cổ phần Thương nghiệp Cà Mau'],
  ['CMX', 'Công ty Cổ phần Camimex Group'],
  ['CNG', 'Công ty Cổ phần CNG Việt Nam'],
  ['COM', 'Công ty Cổ phần Vật tư - Xăng dầu'],
  ['CRC', 'Công ty Cổ phần Create Capital Việt Nam'],
  ['CRE', 'Công ty Cổ phần Bất động sản Thế Kỷ'],
  ['CRV', 'Công ty Cổ phần Tập đoàn Bất động sản CRV'],
  ['CSM', 'Công ty Cổ phần Công nghiệp Cao su Miền Nam'],
  ['CSV', 'Công ty Cổ phần Hóa chất cơ bản miền Nam'],
  ['CTD', 'Công ty Cổ phần Xây dựng COTECCONS'],
  ['CTF', 'Công ty Cổ phần City Auto'],
  ['CTG', 'Ngân hàng Thương mại Cổ phần Công Thương Việt Nam'],
  ['CTI', 'Công ty Cổ phần Đầu tư Phát triển Cường Thuận IDICO'],
  ['CTR', 'Tổng Công ty Cổ phần Công trình Viettel'],
  ['CTS', 'Công ty Cổ phần Chứng khoán VIETINBANK'],
  ['CVT', 'Công ty Cổ phần CMC'],
  ['D2D', 'Công ty Cổ phần Phát triển Đô thị Công nghiệp số 2'],
  ['DAH', 'Công ty Cổ phần Tập đoàn Khách sạn Đông Á'],
  ['DAT', 'Công ty Cổ phần Đầu tư Du lịch và Phát triển Thủy sản'],
  ['DBC', 'Công ty Cổ phần Tập đoàn DABACO Việt Nam'],
  ['DBD', 'Công ty Cổ phần Dược - Trang thiết bị Y tế Bình Định'],
  ['DBT', 'Công ty Cổ phần Dược phẩm Bến Tre'],
  ['DC4', 'Công ty Cổ phần DICERA HOLDINGS'],
  ['DCL', 'Công ty Cổ phần Dược phẩm Cửu Long'],
  ['DCM', 'Công ty Cổ phần - Tổng Công ty phân bón Dầu khí Cà Mau'],
  ['DGC', 'Công ty Cổ phần Tập đoàn Hóa chất Đức Giang'],
  ['DGW', 'Công ty Cổ phần Thế Giới Số'],
  ['DHA', 'Công ty Cổ phần Hóa An'],
  ['DHC', 'Công ty Cổ phần Đông Hải Bến Tre'],
  ['DHG', 'Công ty Cổ phần Dược Hậu Giang'],
  ['DHM', 'Công ty Cổ phần Đầu tư và Thương mại DHM'],
  ['DIG', 'Tổng Công ty Cổ phần Đầu tư Phát triển Xây dựng'],
  ['DLG', 'Công ty Cổ phần Tập đoàn Đức Long Gia Lai'],
  ['DMC', 'Công ty Cổ phần Xuất nhập khẩu Y tế DOMESCO'],
  ['DPG', 'Công ty Cổ phần Tập đoàn Đạt Phương'],
  ['DPM', 'Tổng Công ty Phân bón và Hóa chất Dầu khí - Công ty Cổ phần'],
  ['DPR', 'Công ty Cổ phần Cao su Đồng Phú'],
  ['DQC', 'Công ty Cổ phần Tập đoàn Điện Quang'],
  ['DRC', 'Công ty Cổ phần Cao su Đà Nẵng'],
  ['DRH', 'Công ty Cổ phần DRH Holdings'],
  ['DRL', 'Công ty Cổ phần Thủy điện - Điện lực 3'],
  ['DSC', 'Công ty Cổ phần Chứng khoán DSC'],
  ['DSE', 'Công ty Cổ phần Chứng khoán DNSE'],
  ['DSN', 'Công ty Cổ phần Công viên nước Đầm Sen'],
  ['DTA', 'Công ty Cổ phần Đệ Tam'],
  ['DTL', 'Công ty Cổ phần Đại Thiên Lộc'],
  ['DTT', 'Công ty Cổ phần Kỹ nghệ Đô Thành'],
  ['DVP', 'Công ty Cổ phần Đầu tư và Phát triển Cảng Đình Vũ'],
  ['DXG', 'Công ty Cổ phần Bluemarq Group'],
  ['DXS', 'Công ty Cổ phần Dịch vụ Bất động sản Đất Xanh'],
  ['DXV', 'Công ty Cổ phần Vicem Vật liệu Xây dựng Đà Nẵng'],
  ['EIB', 'Ngân hàng Thương mại Cổ phần Xuất Nhập khẩu Việt Nam'],
  ['ELC', 'Công ty Cổ phần Công nghệ - Viễn thông ELCOM'],
  ['EVE', 'Công ty Cổ phần Everpia'],
  ['EVF', 'CÔNG TY TÀI CHÍNH TỔNG HỢP CỔ PHẦN ĐIỆN LỰC'],
  ['EVG', 'Công ty Cổ phần Tập đoàn Everland'],
  ['FCM', 'Công ty Cổ phần Bê tông Phan Vũ Hà Nam'],
  ['FCN', 'Công ty Cổ phần FECON'],
  ['FDC', 'Công ty Cổ phần Ngoại thương và Phát triển Đầu tư Thành phố Hồ Chí Minh'],
  ['FIR', 'Công ty Cổ phần Địa ốc First Real'],
  ['FIT', 'Công ty Cổ phần Tập đoàn F.I.T'],
  ['FMC', 'Công ty Cổ phần Thực phẩm Sao Ta'],
  ['FPT', 'Công ty Cổ phần FPT'],
  ['FRT', 'Công ty Cổ phần Bán lẻ Kỹ thuật số FPT'],
  ['FTS', 'Công ty Cổ phần Chứng khoán FPT'],
  ['GAS', 'Tổng Công ty Khí Việt Nam - Công ty Cổ phần'],
  ['GDT', 'Công ty Cổ phần Chế biến Gỗ Đức Thành'],
  ['GEE', 'Công ty Cổ phần Điện lực Gelex'],
  ['GEG', 'Công ty Cổ phần Điện Gia Lai'],
  ['GEL', 'Công ty Cổ phần Hạ tầng GELEX'],
  ['GEX', 'Công ty Cổ phần Tập đoàn GELEX'],
  ['GHC', 'Công ty Cổ phần Thủy điện Gia Lai'],
  ['GIL', 'Công ty Cổ phần Sản xuất Kinh doanh Xuất nhập khẩu Bình Thạnh'],
  ['GMD', 'CÔNG TY CỔ PHẦN TẬP ĐOÀN GEMADEPT'],
  ['GMH', 'Công ty Cổ phần Minh Hưng Quảng Trị'],
  ['GSP', 'Công ty Cổ phần Vận tải Sản phẩm Khí Quốc tế'],
  ['GTA', 'Công ty Cổ phần Chế biến Gỗ Thuận An'],
  ['GVR', 'Tập đoàn Công nghiệp Cao su Việt Nam - Công ty Cổ phần'],
  ['HAG', 'Công ty Cổ phần Hoàng Anh Gia Lai'],
  ['HAH', 'Công ty Cổ phần Vận tải và Xếp dỡ Hải An'],
  ['HAP', 'Công ty Cổ phần Tập đoàn HAPACO'],
  ['HAR', 'Công ty Cổ phần Đầu tư Thương mại Bất động sản An Dương Thảo Điền'],
  ['HAS', 'Công ty Cổ phần HACISCO'],
  ['HAX', 'Công ty Cổ phần Dịch vụ Ô tô Hàng Xanh'],
  ['HCD', 'Công ty Cổ phần Đầu tư Sản xuất và Thương mại HCD'],
  ['HCM', 'Công ty Cổ phần Chứng khoán Thành phố Hồ Chí Minh'],
  ['HDB', 'Ngân hàng Thương mại Cổ phần Phát triển Thành phố Hồ Chí Minh'],
  ['HDC', 'Công ty Cổ phần Phát triển nhà Bà Rịa – Vũng Tàu'],
  ['HDG', 'Công ty Cổ phần Tập đoàn Hà Đô'],
  ['HHP', 'Công ty Cổ phần HHP Global'],
  ['HHS', 'Công ty Cổ phần Đầu tư Dịch vụ Hoàng Huy'],
  ['HHV', 'Công ty Cổ phần Đầu tư Hạ tầng Giao thông Đèo Cả'],
  ['HID', 'Công ty Cổ phần Halcom Việt Nam'],
  ['HII', 'Công ty Cổ phần An Tiến Industries'],
  ['HMC', 'Công ty Cổ phần Kim khí Thành phố Hồ Chí Minh - Vnsteel'],
  ['HNA', 'Công ty Cổ phần Thủy điện Hủa Na'],
  ['HPA', 'Công ty Cổ phần Phát triển Nông nghiệp Hòa Phát'],
  ['HPG', 'Công ty Cổ phần Tập đoàn Hòa Phát'],
  ['HPX', 'Công ty Cổ phần Đầu tư Hải Phát'],
  ['HQC', 'Công ty Cổ phần Tư vấn – Thương mại – Dịch vụ Địa ốc Hoàng Quân'],
  ['HRC', 'Công ty Cổ phần Cao su Hòa Bình'],
  ['HSG', 'Công ty Cổ phần Tập đoàn Hoa Sen'],
  ['HSL', 'Công ty Cổ phần Đầu tư Phát triển Thực phẩm Hồng Hà'],
  ['HT1', 'Công ty Cổ phần Xi măng VICEM Hà Tiên'],
  ['HTG', 'Tổng Công ty Cổ phần Dệt may Hòa Thọ'],
  ['HTI', 'Công ty Cổ phần Đầu tư Phát triển Hạ tầng IDICO'],
  ['HTL', 'Công ty Cổ phần Kỹ thuật và Ô tô Trường Long'],
  ['HTN', 'Công ty Cổ phần Hưng Thịnh Incons'],
  ['HTV', 'Công ty Cổ phần Logistics Vicem'],
  ['HU1', 'Công ty Cổ phần Đầu tư và Xây dựng HUD1'],
  ['HUB', 'Công ty Cổ phần Xây lắp Thừa Thiên Huế'],
  ['HVH', 'Công ty Cổ phần Đầu tư và Công nghệ HVC'],
  ['HVN', 'Tổng Công ty Hàng không Việt Nam - CTCP'],
  ['ICT', 'Công ty Cổ phần Viễn thông - Tin học Bưu điện'],
  ['IDI', 'Công ty Cổ phần Đầu tư và Phát triển Đa Quốc Gia I.D.I'],
  ['IJC', 'Công ty Cổ phần Phát triển Hạ tầng Kỹ thuật'],
  ['ILB', 'Công ty Cổ phần ICD Tân Cảng - Long Bình'],
  ['IMP', 'Công ty Cổ phần Dược phẩm Imexpharm'],
  ['ITC', 'Công ty Cổ phần Đầu tư - Kinh doanh Nhà'],
  ['ITD', 'Công ty Cổ phần Công Nghệ ITD'],
  ['JVC', 'Công ty Cổ phần Đầu tư Y tế - Dược Phẩm Việt Nam'],
  ['KBC', 'Tổng Công ty Phát triển Đô Thị Kinh Bắc – Công ty Cổ phần'],
  ['KDC', 'Công ty Cổ phần Tập đoàn Kido'],
  ['KDH', 'Công ty Cổ phần Đầu tư và Kinh doanh Nhà Khang Điền'],
  ['KHG', 'Công ty Cổ phần Tập đoàn Khải Hoàn Land'],
  ['KHP', 'Công ty Cổ phần Điện lực Khánh Hòa'],
  ['KLB', 'Ngân hàng Thương mại Cổ phần Kiên Long'],
  ['KMR', 'Công ty Cổ phần MIRAE'],
  ['KOS', 'Công ty Cổ phần KOSY'],
  ['KSB', 'Công ty Cổ phần Khoáng sản và Xây dựng Bình Dương'],
  ['L10', 'Công ty Cổ phần Lilama 10'],
  ['LAF', 'Công ty Cổ phần Chế biến Hàng xuất khẩu Long An'],
  ['LBM', 'Công ty Cổ phần Khoáng sản và Vật liệu Xây dựng Lâm Đồng'],
  ['LCG', 'Công ty Cổ phần Lizen'],
  ['LDG', 'Công ty Cổ phần Đầu tư LDG'],
  ['LGC', 'Công ty Cổ phần Đầu tư Cầu Đường CII'],
  ['LGL', 'Công ty Cổ phần Đầu tư và Phát triển Đô thị Long Giang'],
  ['LHG', 'Công ty Cổ phần Long Hậu'],
  ['LIX', 'Công ty Cổ phần Bột giặt LIX'],
  ['LM8', 'Công ty Cổ phần Lilama 18'],
  ['LPB', 'Ngân hàng Thương mại Cổ phần Lộc Phát Việt Nam'],
  ['LSS', 'Công ty Cổ phần Mía đường Lam Sơn'],
  ['MBB', 'Ngân hàng Thương mại Cổ phần Quân Đội'],
  ['MCH', 'Công ty cổ phần Hàng tiêu dùng Masan'],
  ['MCM', 'Công ty Cổ phần Giống bò sữa Mộc Châu'],
  ['MCP', 'Công ty Cổ phần In và Bao bì Mỹ Châu'],
  ['MDG', 'Công ty Cổ phần Miền Đông'],
  ['MHC', 'Công ty Cổ phần MHC'],
  ['MIG', 'Tổng Công ty Cổ phần Bảo hiểm Quân đội'],
  ['MSB', 'Ngân hàng Thương mại Cổ phần Hàng Hải Việt Nam'],
  ['MSH', 'Công ty Cổ phần May Sông Hồng'],
  ['MSN', 'Công ty Cổ phần Tập đoàn MaSan'],
  ['MWG', 'Công ty Cổ phần Đầu tư Thế Giới Di Động'],
  ['MZG', 'Công ty Cổ phần Miza'],
  ['NAB', 'Ngân hàng Thương mại Cổ phần Nam Á'],
  ['NAF', 'Công ty Cổ phần Nafoods Group'],
  ['NAV', 'Công ty Cổ phần Nam Việt'],
  ['NBB', 'Công ty Cổ phần Đầu tư Năm Bảy Bảy'],
  ['NCT', 'Công ty Cổ phần Dịch vụ Hàng hóa Nội Bài'],
  ['NHA', 'Tổng Công ty Đầu tư Phát triển Nhà và Đô thị Nam Hà Nội'],
  ['NHH', 'Công ty Cổ phần Nhựa Hà Nội'],
  ['NHT', 'Công ty Cổ phần Sản xuất và Thương mại Nam Hoa'],
  ['NKG', 'Công ty Cổ phần Thép Nam Kim'],
  ['NLG', 'Công ty Cổ phần Đầu tư Nam Long'],
  ['NNC', 'Công ty Cổ phần Đá Núi Nhỏ'],
  ['NO1', 'Công ty Cổ phần Tập đoàn 911'],
  ['NSC', 'Công ty Cổ phần Tập đoàn Giống cây trồng Việt Nam'],
  ['NT2', 'Công ty Cổ phần Điện lực Dầu khí Nhơn Trạch 2'],
  ['NTC', 'Công ty cổ phần Khu Công nghiệp Nam Tân Uyên'],
  ['NTL', 'Công ty Cổ phần Phát triển Đô thị Từ Liêm'],
  ['NVL', 'Công ty Cổ phần Tập đoàn Đầu tư Địa ốc No Va'],
  ['NVT', 'Công ty Cổ phần Bất động sản Du lịch Ninh Vân Bay'],
  ['OCB', 'Ngân hàng Thương mại Cổ phần Phương Đông'],
  ['OGC', 'Công ty Cổ phần Tập đoàn Đại Dương'],
  ['OPC', 'Công ty Cổ phần Dược phẩm OPC'],
  ['ORS', 'Công ty Cổ phần Chứng khoán Tiên Phong'],
  ['PAC', 'Công ty Cổ phần Pin Ắc quy miền Nam'],
  ['PAN', 'Công ty Cổ phần Tập đoàn PAN'],
  ['PC1', 'Công ty Cổ phần Tập đoàn PC1'],
  ['PDN', 'Công ty Cổ phần Cảng Đồng Nai'],
  ['PDR', 'Công ty Cổ phần Phát triển Bất động sản Phát Đạt'],
  ['PDV', 'Công ty Cổ phần Vận tải và Tiếp vận Phương Đông Việt'],
  ['PET', 'Tổng Công ty Cổ phần Dịch vụ Tổng hợp Dầu khí'],
  ['PGC', 'Tổng Công ty Gas Petrolimex - Công ty Cổ phần'],
  ['PGD', 'Công ty Cổ phần Phân phối Khí thấp áp Dầu khí Việt Nam'],
  ['PGI', 'Tổng Công ty Cổ phần Bảo hiểm Petrolimex'],
  ['PGV', 'Tổng Công ty Phát điện 3 - Công ty Cổ phần'],
  ['PHC', 'Công ty Cổ phần Xây dựng Phục Hưng Holdings'],
  ['PHR', 'Công ty Cổ phần Cao su Phước Hòa'],
  ['PIT', 'Công ty Cổ phần Xuất nhập khẩu Petrolimex'],
  ['PJT', 'Công ty Cổ phần Vận tải Xăng dầu Đường thủy Petrolimex'],
  ['PLP', 'Công ty Cổ phần Sản xuất và Công nghệ Nhựa Pha Lê'],
  ['PLX', 'Tập đoàn Xăng dầu Việt Nam'],
  ['PMG', 'Công ty Cổ phần Đầu tư và Sản xuất Petro Miền Trung'],
  ['PNC', 'Công ty Cổ phần Văn hóa Phương Nam'],
  ['PNJ', 'Công ty Cổ phần Vàng bạc Đá quý Phú Nhuận'],
  ['POW', 'Tổng Công ty Điện lực Dầu khí Việt Nam - CTCP'],
  ['PPC', 'Công ty Cổ phần Nhiệt điện Phả Lại'],
  ['PTB', 'Công ty Cổ phần Phú Tài'],
  ['PTC', 'Công ty Cổ phần Đầu tư iCapital'],
  ['PTL', 'Công ty Cổ phần Victory Group'],
  ['PVD', 'Tổng Công ty Cổ phần Khoan và Dịch vụ Khoan Dầu khí'],
  ['PVP', 'Công ty Cổ phần Vận tải Dầu khí Thái Bình Dương'],
  ['PVT', 'Tổng Công ty Cổ phần Vận tải Dầu khí'],
  ['QCG', 'Công ty Cổ phần Quốc Cường Gia Lai'],
  ['QNP', 'Công ty Cổ phần Cảng Quy Nhơn'],
  ['RAL', 'Công ty Cổ phần Bóng đèn Phích nước Rạng Đông'],
  ['REE', 'Công ty Cổ phần Cơ Điện Lạnh'],
  ['RYG', 'Công ty Cổ phần Sản xuất và Đầu tư Hoàng Gia'],
  ['S4A', 'Công ty Cổ phần Thủy điện Sê San 4A'],
  ['SAB', 'Tổng Công ty Cổ phần Bia – Rượu – Nước giải khát Sài Gòn'],
  ['SAM', 'Công ty Cổ phần SAM Holdings'],
  ['SAV', 'Công ty Cổ phần Hợp tác Kinh tế và Xuất nhập khẩu Savimex'],
  ['SBA', 'Công ty Cổ phần Sông Ba'],
  ['SBG', 'Công ty Cổ phần Tập đoàn Cơ khí Công nghệ cao Siba'],
  ['SBT', 'Công ty Cổ phần Thành Thành Công - Biên Hòa'],
  ['SBV', 'Công ty Cổ phần Siam Brothers Việt Nam'],
  ['SC5', 'Công ty Cổ phần Xây dựng Số 5'],
  ['SCR', 'Công ty Cổ phần Địa ốc Sài Gòn Thương Tín'],
  ['SCS', 'Công ty Cổ phần Dịch vụ Hàng hóa Sài Gòn'],
  ['SFC', 'Công ty Cổ phần Nhiên liệu Sài Gòn'],
  ['SFG', 'Công ty Cổ phần Phân bón Miền Nam'],
  ['SFI', 'Công ty Cổ phần Đại lý Vận tải SAFI'],
  ['SGN', 'Công ty Cổ phần Phục vụ Mặt đất Sài Gòn'],
  ['SGR', 'Công ty Cổ phần Tổng Công ty Cổ phần Địa ốc Sài Gòn'],
  ['SGT', 'Công ty Cổ phần Công nghệ Viễn thông Sài Gòn'],
  ['SHA', 'Công ty Cổ phần Sơn Hà Sài Gòn'],
  ['SHB', 'Ngân hàng Thương mại Cổ phần Sài Gòn – Hà Nội'],
  ['SHI', 'Công ty Cổ phần Quốc tế Sơn Hà'],
  ['SHP', 'Công ty Cổ phần Thủy điện Miền Nam'],
  ['SIP', 'Công ty Cổ phần Đầu tư Sài Gòn VRG'],
  ['SJD', 'Công ty Cổ phần Thủy điện Cần Đơn'],
  ['SJS', 'Công ty Cổ phần SJ Group'],
  ['SKG', 'Công ty Cổ phần Tàu cao tốc Superdong – Kiên Giang'],
  ['SMA', 'Công ty Cổ phần Thiết bị Phụ tùng Sài Gòn'],
  ['SMB', 'Công ty Cổ phần Bia Sài Gòn - Miền Trung'],
  ['SMC', 'Công ty Cổ phần Đầu tư Thương mại SMC'],
  ['SPM', 'Công ty Cổ phần S.P.M'],
  ['SRC', 'Công ty Cổ phần Cao su Sao Vàng'],
  ['SRF', 'Công ty Cổ phần SEAREFICO'],
  ['SSB', 'Ngân hàng Thương mại Cổ phần Đông Nam Á'],
  ['SSC', 'Công ty Cổ phần Giống Cây trồng Miền Nam'],
  ['SSI', 'Công ty Cổ phần Chứng khoán SSI'],
  ['ST8', 'Công ty Cổ phần Tập đoàn ST8'],
  ['STB', 'Ngân hàng thương mại cổ phần Sài Gòn Tài Lộc'],
  ['STG', 'Công ty Cổ phần Kho vận Miền Nam'],
  ['STK', 'Công ty Cổ phần Sợi Thế Kỷ'],
  ['SVC', 'Công ty Cổ phần Dịch vụ Tổng hợp Sài Gòn'],
  ['SVD', 'Công ty Cổ phần Đầu tư & Thương mại Vũ Đăng'],
  ['SVT', 'Công ty Cổ phần Công nghệ Sài Gòn Viễn Đông'],
  ['SZC', 'Công ty Cổ phần Sonadezi Châu Đức'],
  ['SZL', 'Công ty Cổ phần Sonadezi Long Thành'],
  ['TAL', 'Công ty cổ phần Đầu tư Bất động sản Taseco'],
  ['TBC', 'Công ty Cổ phần Thủy điện Thác Bà'],
  ['TCB', 'Ngân hàng Thương mại Cổ phần Kỹ Thương Việt Nam'],
  ['TCH', 'Công ty Cổ phần Đầu tư Dịch vụ Tài chính Hoàng Huy'],
  ['TCI', 'Công ty Cổ phần Chứng khoán Thành Công'],
  ['TCL', 'Công ty Cổ phần Đại lý Giao nhận Vận tải Xếp dỡ Tân Cảng'],
  ['TCM', 'Công ty Cổ phần Dệt may - Đầu tư - Thương mại Thành Công'],
  ['TCO', 'CÔNG TY CỔ PHẦN JANUS GROUP'],
  ['TCR', 'Công ty Cổ phần Công nghiệp Gốm sứ TAICERA'],
  ['TCT', 'Công ty Cổ phần Cáp treo Núi Bà Tây Ninh'],
  ['TCX', 'Công ty cổ phần Chứng khoán Kỹ Thương'],
  ['TDC', 'Công ty Cổ phần Kinh doanh và Phát triển Bình Dương'],
  ['TDG', 'Công ty Cổ phần Đầu tư TDG GLOBAL'],
  ['TDH', 'Công ty Cổ phần Phát triển Nhà Thủ Đức'],
  ['TDM', 'Công ty Cổ phần Nước Thủ Dầu Một'],
  ['TDP', 'Công ty Cổ phần Thuận Đức'],
  ['TDW', 'Công ty Cổ phần Cấp nước Thủ Đức'],
  ['TEG', 'Công ty Cổ phần Trường Thành Energy Group'],
  ['THG', 'Công ty Cổ phần Đầu tư và Xây dựng Tiền Giang'],
  ['TIP', 'Công ty Cổ phần Phát triển Khu Công nghiệp Tín Nghĩa'],
  ['TIX', 'Công ty Cổ phần Sản xuất Kinh doanh XNK Dịch vụ và Đầu tư Tân Bình'],
  ['TLD', 'Công ty Cổ phần Đầu tư Xây dựng và Phát triển Đô thị Thăng Long'],
  ['TLG', 'Công ty Cổ phần Tập đoàn Thiên Long'],
  ['TLH', 'Công ty Cổ phần Tập đoàn Thép Tiến Lên'],
  ['TMP', 'Công ty Cổ phần Thủy điện Thác Mơ'],
  ['TMS', 'Công ty Cổ phần Transimex'],
  ['TMT', 'Công ty Cổ phần Ô tô TMT'],
  ['TN1', 'Công ty Cổ phần ROX Key Holdings'],
  ['TNC', 'Công ty Cổ phần Cao su Thống Nhất'],
  ['TNH', 'Công ty Cổ phần Tập đoàn Bệnh viện TNH'],
  ['TNI', 'Công ty Cổ phần Tập đoàn Thành Nam'],
  ['TNT', 'Công ty Cổ phần Tập đoàn TNT'],
  ['TPB', 'Ngân hàng Thương mại Cổ phần Tiên Phong'],
  ['TPC', 'Công ty Cổ phần Nhựa Tân Đại Hưng'],
  ['TRA', 'Công ty Cổ phần Traphaco'],
  ['TRC', 'Công ty Cổ phần Cao su Tây Ninh'],
  ['TSA', 'Công ty Cổ phần Đầu tư và Xây lắp Trường Sơn'],
  ['TSC', 'Công ty Cổ phần Vật tư Kỹ thuật Nông nghiệp Cần Thơ'],
  ['TTA', 'Công ty Cổ phần Đầu tư Xây dựng và Phát triển Trường Thành'],
  ['TTE', 'Công ty Cổ phần Đầu tư Năng lượng Trường Thịnh'],
  ['TTF', 'Công ty Cổ phần Tập đoàn Kỹ nghệ Gỗ Trường Thành'],
  ['TV2', 'Công ty Cổ phần Tư vấn Xây dựng Điện 2'],
  ['TVB', 'Công ty Cổ phần Chứng khoán T-Cap'],
  ['TVS', 'Công ty Cổ phần Chứng khoán Thiên Việt'],
  ['TVT', 'Tổng Công ty Việt Thắng - CTCP'],
  ['TYA', 'Công ty Cổ phần Dây và Cáp điện Taya Việt Nam'],
  ['UIC', 'Công ty Cổ phần Đầu tư Phát triển Nhà và Đô thị IDICO'],
  ['VAB', 'Ngân hàng Thương mại cổ phần Việt Á'],
  ['VBB', 'Ngân hàng Thương mại Cổ phần Việt Nam Thương Tín'],
  ['VCA', 'Công ty Cổ phần Thép VICASA'],
  ['VCB', 'Ngân hàng Thương mại Cổ phần Ngoại Thương Việt Nam'],
  ['VCF', 'Công ty Cổ phần VINACAFÉ Biên Hòa'],
  ['VCG', 'Tổng Công ty Cổ phần Xuất nhập khẩu và Xây dựng Việt Nam'],
  ['VCI', 'Công ty Cổ phần Chứng khoán Vietcap'],
  ['VCK', 'Công ty Cổ phần Chứng khoán VPS'],
  ['VDP', 'Công ty Cổ phần Dược phẩm Trung Ương Vidipha'],
  ['VDS', 'Công ty Cổ phần Chứng khoán Rồng Việt'],
  ['VFG', 'Công ty Cổ phần Khử trùng Việt Nam'],
  ['VGC', 'Tổng Công ty Viglacera - CTCP'],
  ['VHC', 'Công ty Cổ phần Vĩnh Hoàn'],
  ['VHM', 'Công ty Cổ phần Vinhomes'],
  ['VIB', 'Ngân hàng Thương mại Cổ phần Quốc tế Việt Nam'],
  ['VIC', 'Tập đoàn Vingroup - Công ty Cổ phần'],
  ['VID', 'Công ty Cổ phần Đầu tư Phát triển Thương mại Viễn Đông'],
  ['VIP', 'Công ty Cổ phần Vận tải Xăng dầu VIPCO'],
  ['VIX', 'Công ty Cổ phần Chứng khoán VIX'],
  ['VJC', 'Công ty Cổ phần Hàng không VietJet'],
  ['VMD', 'Công ty Cổ phần Y Dược phẩm Vimedimex'],
  ['VND', 'Công ty Cổ phần Chứng khoán VNDIRECT'],
  ['VNG', 'Công ty Cổ phần Du lịch Thành Thành Công'],
  ['VNL', 'Công ty Cổ phần Logistics Vinalink'],
  ['VNM', 'Công ty Cổ phần Sữa Việt Nam'],
  ['VNS', 'Công ty Cổ phần Ánh Dương Việt Nam'],
  ['VOS', 'Công ty Cổ phần Vận tải Biển Việt Nam'],
  ['VPB', 'Ngân hàng Thương mại Cổ phần Việt Nam Thịnh Vượng'],
  ['VPD', 'Công ty Cổ phần Phát triển Điện lực Việt Nam'],
  ['VPG', 'Công ty Cổ phần Đầu tư Thương mại Xuất nhập khẩu Việt Phát'],
  ['VPH', 'Công ty Cổ phần Vạn Phát Hưng'],
  ['VPI', 'Công ty Cổ phần Phát triển BĐS Văn Phú'],
  ['VPL', 'Công ty cổ phần Vinpearl'],
  ['VPS', 'Công ty Cổ phần Thuốc sát trùng Việt Nam'],
  ['VPX', 'Công ty cổ phần Chứng khoán VPBANK'],
  ['VRC', 'Công ty Cổ phần Bất động sản và Đầu tư VRC'],
  ['VRE', 'Công ty Cổ phần Vincom Retail'],
  ['VSC', 'Công ty Cổ phần Container Việt Nam'],
  ['VSH', 'Công ty Cổ phần Thủy điện Vĩnh Sơn - Sông Hinh'],
  ['VSI', 'Công ty Cổ phần Đầu tư và Xây dựng Cấp thoát nước'],
  ['VTB', 'Công ty Cổ phần Viettronics Tân Bình'],
  ['VTO', 'Công ty Cổ phần Vận tải Xăng dầu VITACO'],
  ['VTP', 'Tổng Công ty Cổ phần Bưu chính Viettel'],
  ['VVS', 'Công ty cổ phần Đầu tư phát triển máy Việt Nam'],
  ['YBM', 'Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái'],
  ['YEG', 'Công ty Cổ phần Tập đoàn Yeah1'],
]

/** Số mã lúc sinh file, để test canh được nếu lần hút sau bị cắt cụt. */
export const HOSE_SYMBOL_COUNT = 403
